-- Debt tracker schema.
--
-- Hybrid shape: debts and their per-rate balances are normalised so they can be
-- queried in SQL; imported statement history is kept as JSONB because its shape
-- follows whatever the issuer's file happened to contain.
--
-- Ids are text rather than uuid so that data already sitting in a browser's
-- localStorage uploads unchanged. New ids are uuids generated by the client.

-- ---------------------------------------------------------------- settings --

create table if not exists public.settings (
  user_id         uuid primary key references auth.users on delete cascade,
  monthly_budget  numeric(12, 2) not null default 1000,
  start_date      date           not null default current_date,
  strategy        text           not null default 'avalanche'
                    check (strategy in ('avalanche', 'snowball', 'cashflow', 'deadline')),
  updated_at      timestamptz    not null default now()
);

-- ------------------------------------------------------------------- debts --

create table if not exists public.debts (
  id          text primary key,
  user_id     uuid not null references auth.users on delete cascade,
  kind        text not null check (kind in ('credit_card', 'loan')),
  name        text not null,
  position    integer not null default 0,
  notes       text,

  -- credit card columns
  issuer                       text,
  credit_limit                 numeric(12, 2),
  statement_day                smallint check (statement_day between 1 and 31),
  due_day                      smallint check (due_day between 1 and 31),
  min_payment_pct              numeric(6, 3),
  min_payment_floor            numeric(12, 2),
  min_includes_interest        boolean,
  paid_in_full_last_statement  boolean,

  -- loan columns
  lender              text,
  balance             numeric(12, 2),
  apr                 numeric(6, 3),
  payment_frequency   text check (payment_frequency in ('monthly', 'biweekly', 'semimonthly', 'weekly')),
  payment_amount      numeric(12, 2),
  next_payment_date   date,
  informal            boolean,

  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  -- A row must carry the columns its kind actually needs.
  constraint debts_credit_card_shape check (
    kind <> 'credit_card' or (
      statement_day is not null and due_day is not null and
      min_payment_pct is not null and min_payment_floor is not null and
      min_includes_interest is not null
    )
  ),
  constraint debts_loan_shape check (
    kind <> 'loan' or (
      balance is not null and apr is not null and
      payment_frequency is not null and payment_amount is not null and
      next_payment_date is not null
    )
  )
);

create index if not exists debts_user_idx on public.debts (user_id, position);

-- ------------------------------------------------------------ card buckets --

-- One row per distinct rate on a card: purchases, a 0% transfer, a flex plan.
create table if not exists public.card_buckets (
  id        text primary key,
  debt_id   text not null references public.debts on delete cascade,
  user_id   uuid not null references auth.users on delete cascade,
  position  integer not null default 0,

  label     text not null,
  kind      text not null check (kind in ('purchase', 'balance_transfer', 'flex_plan', 'cash_advance')),
  balance   numeric(12, 2) not null default 0 check (balance >= 0),
  apr       numeric(6, 3)  not null default 0 check (apr >= 0),

  promo_apr          numeric(6, 3) check (promo_apr >= 0),
  promo_end_date     date,
  deferred_interest  boolean not null default false,

  flex_monthly_payment   numeric(12, 2),
  flex_monthly_fee_pct   numeric(6, 3),
  flex_original_amount   numeric(12, 2),
  flex_remaining_months  integer,

  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists card_buckets_debt_idx on public.card_buckets (debt_id, position);

-- -------------------------------------------------------------- statements --

create table if not exists public.statements (
  id           text primary key,
  user_id      uuid not null references auth.users on delete cascade,
  debt_id      text references public.debts on delete cascade,
  close_date   date not null,
  source       text not null check (source in ('manual', 'csv', 'pdf')),
  data         jsonb not null,
  imported_at  timestamptz not null default now()
);

create index if not exists statements_user_idx on public.statements (user_id, close_date desc);

-- --------------------------------------------------------------------- RLS --

alter table public.settings     enable row level security;
alter table public.debts        enable row level security;
alter table public.card_buckets enable row level security;
alter table public.statements   enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array['settings', 'debts', 'card_buckets', 'statements'] loop
    execute format('drop policy if exists %I_owner on public.%I', t, t);
    execute format(
      'create policy %I_owner on public.%I
         for all
         using (auth.uid() = user_id)
         with check (auth.uid() = user_id)',
      t, t
    );
  end loop;
end $$;

-- ------------------------------------------------------------ save_state() --

-- Replaces the caller's entire state in one transaction. A partial write would
-- leave balances and buckets disagreeing, so this is deliberately all-or-nothing.
-- security invoker keeps RLS in force: the function can only touch the caller's
-- own rows even though it is issuing unqualified deletes.
create or replace function public.save_state(payload jsonb)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;

  -- settings
  insert into public.settings (user_id, monthly_budget, start_date, strategy, updated_at)
  values (
    uid,
    coalesce((payload -> 'settings' ->> 'monthlyBudget')::numeric, 1000),
    coalesce((payload -> 'settings' ->> 'startDate')::date, current_date),
    coalesce(payload -> 'settings' ->> 'strategy', 'avalanche'),
    now()
  )
  on conflict (user_id) do update set
    monthly_budget = excluded.monthly_budget,
    start_date     = excluded.start_date,
    strategy       = excluded.strategy,
    updated_at     = now();

  -- debts removed on the client
  -- not exists rather than not in: a null id in the payload would make
  -- "not in" match nothing and silently skip the cleanup.
  delete from public.debts d
  where d.user_id = uid
    and not exists (
      select 1
      from jsonb_array_elements(coalesce(payload -> 'debts', '[]'::jsonb)) x
      where x ->> 'id' = d.id
    );

  insert into public.debts (
    id, user_id, kind, name, position, notes,
    issuer, credit_limit, statement_day, due_day,
    min_payment_pct, min_payment_floor, min_includes_interest, paid_in_full_last_statement,
    lender, balance, apr, payment_frequency, payment_amount, next_payment_date, informal,
    updated_at
  )
  select
    d ->> 'id',
    uid,
    d ->> 'kind',
    d ->> 'name',
    ord - 1,
    d ->> 'notes',
    d ->> 'issuer',
    (d ->> 'creditLimit')::numeric,
    (d ->> 'statementDay')::smallint,
    (d ->> 'dueDay')::smallint,
    (d ->> 'minPaymentPct')::numeric,
    (d ->> 'minPaymentFloor')::numeric,
    (d ->> 'minIncludesInterest')::boolean,
    (d ->> 'paidInFullLastStatement')::boolean,
    d ->> 'lender',
    (d ->> 'balance')::numeric,
    (d ->> 'apr')::numeric,
    d ->> 'paymentFrequency',
    (d ->> 'paymentAmount')::numeric,
    (d ->> 'nextPaymentDate')::date,
    (d ->> 'informal')::boolean,
    now()
  from jsonb_array_elements(coalesce(payload -> 'debts', '[]'::jsonb)) with ordinality as t(d, ord)
  on conflict (id) do update set
    kind                        = excluded.kind,
    name                        = excluded.name,
    position                    = excluded.position,
    notes                       = excluded.notes,
    issuer                      = excluded.issuer,
    credit_limit                = excluded.credit_limit,
    statement_day               = excluded.statement_day,
    due_day                     = excluded.due_day,
    min_payment_pct             = excluded.min_payment_pct,
    min_payment_floor           = excluded.min_payment_floor,
    min_includes_interest       = excluded.min_includes_interest,
    paid_in_full_last_statement = excluded.paid_in_full_last_statement,
    lender                      = excluded.lender,
    balance                     = excluded.balance,
    apr                         = excluded.apr,
    payment_frequency           = excluded.payment_frequency,
    payment_amount              = excluded.payment_amount,
    next_payment_date           = excluded.next_payment_date,
    informal                    = excluded.informal,
    updated_at                  = now();

  -- buckets removed on the client
  delete from public.card_buckets b
  where b.user_id = uid
    and not exists (
      select 1
      from jsonb_array_elements(coalesce(payload -> 'debts', '[]'::jsonb)) d,
           jsonb_array_elements(coalesce(d -> 'buckets', '[]'::jsonb)) bk
      where bk ->> 'id' = b.id
    );

  insert into public.card_buckets (
    id, debt_id, user_id, position, label, kind, balance, apr,
    promo_apr, promo_end_date, deferred_interest,
    flex_monthly_payment, flex_monthly_fee_pct, flex_original_amount, flex_remaining_months,
    updated_at
  )
  select
    bk ->> 'id',
    d ->> 'id',
    uid,
    ord - 1,
    bk ->> 'label',
    bk ->> 'kind',
    coalesce((bk ->> 'balance')::numeric, 0),
    coalesce((bk ->> 'apr')::numeric, 0),
    (bk ->> 'promoApr')::numeric,
    nullif(bk ->> 'promoEndDate', '')::date,
    coalesce((bk ->> 'deferredInterest')::boolean, false),
    (bk ->> 'flexMonthlyPayment')::numeric,
    (bk ->> 'flexMonthlyFeePct')::numeric,
    (bk ->> 'flexOriginalAmount')::numeric,
    (bk ->> 'flexRemainingMonths')::integer,
    now()
  from jsonb_array_elements(coalesce(payload -> 'debts', '[]'::jsonb)) d,
       jsonb_array_elements(coalesce(d -> 'buckets', '[]'::jsonb)) with ordinality as t(bk, ord)
  on conflict (id) do update set
    debt_id               = excluded.debt_id,
    position              = excluded.position,
    label                 = excluded.label,
    kind                  = excluded.kind,
    balance               = excluded.balance,
    apr                   = excluded.apr,
    promo_apr             = excluded.promo_apr,
    promo_end_date        = excluded.promo_end_date,
    deferred_interest     = excluded.deferred_interest,
    flex_monthly_payment  = excluded.flex_monthly_payment,
    flex_monthly_fee_pct  = excluded.flex_monthly_fee_pct,
    flex_original_amount  = excluded.flex_original_amount,
    flex_remaining_months = excluded.flex_remaining_months,
    updated_at            = now();

  -- statements are append-only history, so they are upserted but never deleted
  insert into public.statements (id, user_id, debt_id, close_date, source, data, imported_at)
  select
    s ->> 'id',
    uid,
    s ->> 'debtId',
    (s ->> 'closeDate')::date,
    coalesce(s ->> 'source', 'manual'),
    s,
    coalesce((s ->> 'importedAt')::timestamptz, now())
  from jsonb_array_elements(coalesce(payload -> 'statements', '[]'::jsonb)) s
  on conflict (id) do update set
    debt_id    = excluded.debt_id,
    close_date = excluded.close_date,
    source     = excluded.source,
    data       = excluded.data;
end $$;

revoke all on function public.save_state(jsonb) from public;
grant execute on function public.save_state(jsonb) to authenticated;
